name: Release
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Release
        uses: ./.github/workflows/build.yml

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs
